/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wangyu_jnitest_User */

#ifndef _Included_com_wangyu_jnitest_User
#define _Included_com_wangyu_jnitest_User
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wangyu_jnitest_User
 * Method:    getAge
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_wangyu_jnitest_User_getAge
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_wangyu_jnitest_User
 * Method:    getName
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wangyu_jnitest_User_getName
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_wangyu_jnitest_User
 * Method:    getAddress
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wangyu_jnitest_User_getAddress
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
